config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "/ask", to: "questions#ask"
  get "/answer", to: "questions#answer"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def ask
  end

  def answer
    @question = params[:q]
    @answer = ''

    if @question.present?
      if @question.include?("?")
        @answer = 'Silly question, get dressed and go to work!'
      elsif @question === 'I am going to work'
        @answer = 'Great!'
      else
        @answer = 'I don\'t care, get dressed and go to work!'
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsStupidCoaching</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/questions/answer.html.erb
<br>
<br>

<div class="quote question">
  <blockquote>
    <h3>🙋🏻‍♀️ : <%= @question %></h3>
  <blockquote>
</div>
<div class="quote answer">
  <blockquote>
    <h3>👴🏻 : <%= @answer %></h3>
    <p>
  <blockquote>
</div>
<br>
<button class="btn-ask"><%= link_to "Ask a new question", ask_path %></button>

app/views/questions/ask.html.erb
<hr>
<br>
<br>
<form action="/answer" method="get">
  <input type="text" name="q" placeholder="Ask the coach!" class="form--input">
  <input type="submit" value="Ask!" class="btn-purple">
</form>